### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [Anrijs/Aranet4-Python#6]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1.3.post1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary aranet4 -w /tmp/ext aranet4==1.1.3.post1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting aranet4==1.1.3.post1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/6c3/42f18b08bd1f8/aranet4-1.1.3.post1.tar.gz (5.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-cxjd0a5y/aranet4/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-cxjd0a5y/aranet4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-cxjd0a5y/aranet4/pip-egg-info
         cwd: /tmp/pip-wheel-cxjd0a5y/aranet4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-cxjd0a5y/aranet4/setup.py", line 3, in <module>
        with open("aranet4/README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'aranet4/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
It would appear that the setup.py isn't checked in?
